#!/usr/bin/env bash
# source along with bashrc when doing cryptography
if [[ -f "${HOME}/.keychain/$(hostname)-sh" ]]
then
    source "${HOME}/.keychain/$(hostname)-sh" > /dev/null
fi

if [[ -f "${HOME}/.keychain/$(hostname)-sh-gpg" ]]
then
    source "${HOME}/.keychain/$(hostname)-sh-gpg" > /dev/null
fi
