#!/bin/bash
#
# Copyright (C) 2016-2018, Andrew Kroshko, all rights reserved.
#
# Author: Andrew Kroshko
# Maintainer: Andrew Kroshko <akroshko.public+devel@gmail.com>
# Created: Tue May 25, 2016
# Version: 20180918
# URL: https://github.com/akroshko/crypt-profiles
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see http://www.gnu.org/licenses/.

# replace the <<>> with the desired value
export BACKUPHOSTNAME="<<hostname>>"                              # the hostname allowed for backup
export BACKUPUUID="<<backup drive UUID>>"                         # the UUID of the backup drive
export CRYPTGPGKEY="<<path of public key to import>>"             # file with the public key if not already imported
export CRYPTGPGUSER="<<name or email of user>>"                   # the user of the public key to use in general
export CRYPTGPGCONFIGPATH="<<path with gpg.conf/gpg-agent.conf>>" # directory containing a standard gpg.conf and gpg-agent.conf
export CRYPTSSHCONFIGPATH="<<path with config for SSH>>"          # directory with standard ssh_config configuration file
