#!/bin/bash
#
# Copyright (C) 2016, Andrew Kroshko, all rights reserved.
#
# Author: Andrew Kroshko
# Maintainer: Andrew Kroshko <akroshko.public+devel@gmail.com>
# Created: Tue May 25, 2016
# Version: 20160716
# URL: https://github.com/akroshko/crypt-profiles
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see http://www.gnu.org/licenses/.

# source along with bashrc when doing cryptography
if [[ -f "${HOME}/.keychain/${HOSTNAME}-sh" ]];then
    source "${HOME}/.keychain/${HOSTNAME}-sh" >/dev/null
fi
# TODO: I don't use this
# if [[ -f "${HOME}/.keychain/${hostname}-sh-gpg" ]]; then
#     source "${HOME}/.keychain/${HOSTNAME}-sh-gpg" >/dev/null
# fi
# XXXX: duplicate from bash_profile_crypt
envfile="${HOME}/.gnupg/gpg-agent-info-${HOSTNAME}"
if [[ -e "$envfile" ]] && kill -0 "$(grep GPG_AGENT_INFO $envfile | cut -d: -f 2)" 2>/dev/null;then
    DISPLAY= source $envfile
    export GPG_AGENT_INFO
fi
